#!/usr/bin/env python3
"""
Module: factors
Description: RSA factoring problem.
"""
import sys


# get data
filename = sys.argv[1]
f = open(filename, mode="r", encoding="utf-8")
d = f.readlines()
f.close()

# convert to int
d = [int(item[:-1]) for item in d if item.endswith("\n")]


def prime_numbers(number: int) -> list:
    """Generate primes less than nuumber."""
    n = 3  # first prime
    primes = [2]
    while (n < number):
        check = []
        for prime in primes:
            R = n % prime
            check.append(R)
        if min(check) == 0:
            pass
        else:
            primes.append(n)
        n += 1
    return primes


def rsa_factoring(item: int) -> None:
    """Implement the RSA factoring problem."""
    primes = prime_numbers(item)
    inner_list = primes.copy()
    flag = False
    for x in primes:
        for xx in inner_list:
            prod = x * xx
            if prod == item:
                flag = True
                print("{}={}*{}".format(item, x, xx))
                break
        if flag:
            break
        if (len(inner_list) != 0):
            inner_list.pop(0)
    return None


if __name__ == "__main__":
    rsa_factoring(d[0])
